CREATE DATABASE customer_behaviour;

USE customer_behaviour;

RENAME TABLE customer_shopping_cleaned TO shopping_data;

SELECT *
FROM shopping_data
LIMIT 15;


-- Q1 What is the revenue generated by male vs female customers?

SELECT 
    gender,
    SUM(purchase_amount_usd) AS Revenue
FROM shopping_data
GROUP BY gender;


-- Q2 Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id,
    purchase_amount_usd
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount_usd > (
    SELECT AVG(purchase_amount_usd)
    FROM shopping_data
);


-- Q3 Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average Product Rating'
FROM shopping_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4 Compare the average purchase amount between Standard and Express shipping.

SELECT 
    shipping_type,
    AVG(purchase_amount_usd) AS 'Average Purchase Amount'
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5 Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS 'Total Customers',
    AVG(purchase_amount_usd) AS 'Average Spend',
    SUM(purchase_amount_usd) AS 'Total Revenue'
FROM shopping_data
GROUP BY subscription_status;


-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased AS 'Product Purchased',
    (
        COUNT(CASE 
            WHEN discount_applied = 'Yes' THEN 1
        END) * 100.0 / COUNT(*)
    ) AS 'Discount Percentage'
FROM shopping_data
GROUP BY item_purchased
ORDER BY `Discount Percentage` DESC
LIMIT 5;


-- Q7 Segment customers into New, Returning, and Loyal
-- based on their total number of previous purchases
-- and show the count of each segment.

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM shopping_data
)

SELECT 
    customer_segment,
    COUNT(*) AS 'Number Of Customers'
FROM customer_type
GROUP BY customer_segment;


-- Q8 What are the top 3 most purchased products within each category?

WITH product_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS ranking
    FROM shopping_data
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_purchases
FROM product_count
WHERE ranking <= 3;


-- Q9 Are customers who are repeat buyers
-- (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10 What is the revenue contribution of each age group?

SELECT 
    age_group AS 'Age Group',
    SUM(purchase_amount_usd) AS 'Total Revenue'
FROM shopping_data
GROUP BY age_group;